export default [
  { value: "vba", label: "VBA", name: "category" },
  { value: "powerpivot", label: "Power Pivot", name: "category" },
  { value: "dax", label: "DAX", name: "category" },
  { value: "powerquery", label: "Power Query", name: "category" },
  { value: "powerbi", label: "Power BI", name: "category" },
  { value: "powerplatform", label: "Power Platform", name: "category" },
  { value: "dynamics365", label: "Dynamics 365", name: "category" },
  { value: "azure", label: "Azure", name: "category" },
  { value: "tableau", label: "Tableau", name: "category" },
  { value: "qlik", label: "Qlik", name: "category" },
  { value: "word", label: "Word", name: "category" },
  { value: "powerpoint", label: "PowerPoint", name: "category" },
  { value: "outlook", label: "Outlook", name: "category" },
  { value: "access", label: "Access", name: "category" },
  { value: "templates", label: "Templates", name: "category" },
  { value: "financialmodeling", label: "Financial Modeling", name: "category" },
  { value: "dashboard", label: "Dashboard", name: "category" },
  { value: "dataanalytics", label: "Data Analytics", name: "category" },
  { value: "datascience", label: "Data Science", name: "category" },
  { value: "ai", label: "AI", name: "category" },
  { value: "machinelearning", label: "Machine Learning", name: "category" },
  { value: "sql", label: "SQL", name: "category" },
  { value: "sharepoint", label: "SharePoint", name: "category" },
  { value: "python", label: "Python", name: "category" },
  { value: "rlanguage", label: "R Language", name: "category" },
  { value: "data", label: "Data", name: "category" },
];
