export default [
  { value: "Albania", label: "Albania", name: "location" },
  { value: "Andorra", label: "Andorra", name: "location" },
  { value: "Austria", label: "Austria", name: "location" },
  { value: "Azerbaijan", label: "Azerbaijan", name: "location" },
  { value: "Belarus", label: "Belarus", name: "location" },
  { value: "Belgium", label: "Belgium", name: "location" },
  {
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    name: "location",
  },
  { value: "Bulgaria", label: "Bulgaria", name: "location" },
  { value: "Croatia", label: "Croatia", name: "location" },
  { value: "Cyprus", label: "Cyprus", name: "location" },
  { value: "Czech Republic", label: "Czech Republic", name: "location" },
  { value: "Denmark", label: "Denmark", name: "location" },
  { value: "Estonia", label: "Estonia", name: "location" },
  { value: "Finland", label: "Finland", name: "location" },
  { value: "France", label: "France", name: "location" },
  { value: "Germany", label: "Germany", name: "location" },
  { value: "Greece", label: "Greece", name: "location" },
  { value: "Hungary", label: "Hungary", name: "location" },
  { value: "Iceland", label: "Iceland", name: "location" },
  { value: "Ireland", label: "Ireland", name: "location" },
  { value: "Italy", label: "Italy", name: "location" },
  { value: "Kosovo", label: "Kosovo", name: "location" },
  { value: "Latvia", label: "Latvia", name: "location" },
  { value: "Liechtenstein", label: "Liechtenstein", name: "location" },
  { value: "Lithuania", label: "Lithuania", name: "location" },
  { value: "Luxembourg", label: "Luxembourg", name: "location" },
  { value: "Malta", label: "Malta", name: "location" },
  { value: "Moldova", label: "Moldova", name: "location" },
  { value: "Monaco", label: "Monaco", name: "location" },
  { value: "Montenegro", label: "Montenegro", name: "location" },
  { value: "Netherlands", label: "Netherlands", name: "location" },
  { value: "North Macedonia", label: "North Macedonia", name: "location" },
  { value: "Norway", label: "Norway", name: "location" },
  { value: "Poland", label: "Poland", name: "location" },
  { value: "Portugal", label: "Portugal", name: "location" },
  { value: "Romania", label: "Romania", name: "location" },
  { value: "Russia", label: "Russia", name: "location" },
  { value: "San Marino", label: "San Marino", name: "location" },
  { value: "Serbia", label: "Serbia", name: "location" },
  { value: "Slovakia", label: "Slovakia", name: "location" },
  { value: "Slovenia", label: "Slovenia", name: "location" },
  { value: "Spain", label: "Spain", name: "location" },
  { value: "Sweden", label: "Sweden", name: "location" },
  { value: "Switzerland", label: "Switzerland", name: "location" },
  { value: "Ukraine", label: "Ukraine", name: "location" },
  { value: "United Kingdom", label: "United Kingdom", name: "location" },
  { value: "Vatican City", label: "Vatican City", name: "location" },
];
